<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-60T9RMS" failures="8" tests="47" name="Chrome test" time="92.658" errors="0" timestamp="2023-02-06T21:07:48 CET">
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedOutTest" name="deleteAccountButtonNotDisplayed" time="0.035"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedOutTest" name="deleteAllBooksButtonNotDisplayed" time="0.061"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="existingUserCanLogIn" time="4.788"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedOutTest" name="goToBookstoreButtonNotDisplayed" time="0.013"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedInTest" name="goToBookstorePage" time="1.954"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedOutTest" name="goToLoginPageTest" time="2.164"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="3.981">
    <failure type="java.lang.AssertionError" message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.invalidUsernameValidPassword(LoginPageWhenLoggedOutTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- invalidUsernameValidPassword -->
  <testcase classname="tests.login_page.LoginPageWhenLoggedInTest" name="goToProfilePage" time="3.121"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedOutTest" name="goToRegistrationPage" time="1.585"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedInTest" name="loginButtonNotDisplayed" time="0.053"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedInTest" name="logInButtonNotDisplayed" time="0.021"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedOutTest" name="loggedInUserNameNotDisplayed" time="2.105"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedInTest" name="logout" time="0.536"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="3.998">
    <failure type="java.lang.AssertionError" message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.invalidUsernameValidPassword(LoginPageWhenLoggedOutTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- invalidUsernameValidPassword -->
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedOutTest" name="logoutButtonNotDisplayed" time="0.019"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedOutTest" name="nextButtonNotDisplayed" time="0.206"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedInTest" name="newUserShouldHaveZeroBooks" time="0.089"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedOutTest" name="previousButtonNotDisplayed" time="0.025"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedOutTest" name="searchBoxNotDisplayed" time="0.017"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="3.912">
    <failure type="java.lang.AssertionError" message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.invalidUsernameValidPassword(LoginPageWhenLoggedOutTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- invalidUsernameValidPassword -->
  <testcase classname="tests.login_page.LoginPageWhenLoggedInTest" name="logout" time="2.901"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedOutTest" name="settingBooksPerPageNotDisplayed" time="0.021"/>
  <testcase classname="tests.profile_page.ProfilePageWhenLoggedInTest" name="registerButtonNotDisplayed" time="0.06"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedInTest" name="newUserButtonNotDisplayed" time="0.014"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="1.423"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="1.157"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="1.311"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedInTest" name="passwordFieldNotDisplayed" time="0.021"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedInTest" name="usernameFieldNotDisplayed" time="0.011"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="2.777">
    <failure type="java.lang.AssertionError" message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.invalidUsernameValidPassword(LoginPageWhenLoggedOutTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- invalidUsernameValidPassword -->
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="1.192"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="1.207"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="loggedInUserNameNotShown" time="0.014"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="logoutButtonNotDisplayed" time="0.01"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="noPassword" time="2.651"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="noUsername" time="2.653"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="noUsernameNoPassword" time="0.547"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="profileButtonNotDisplayed" time="0.014"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="2.638">
    <failure type="java.lang.AssertionError" message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.validUsernameInvalidPassword(LoginPageWhenLoggedOutTest.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- validUsernameInvalidPassword -->
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="1.171"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="1.028"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="1.081"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="2.582">
    <failure type="java.lang.AssertionError" message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.validUsernameInvalidPassword(LoginPageWhenLoggedOutTest.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- validUsernameInvalidPassword -->
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="2.638">
    <failure type="java.lang.AssertionError" message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.validUsernameInvalidPassword(LoginPageWhenLoggedOutTest.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- validUsernameInvalidPassword -->
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="2.58">
    <failure type="java.lang.AssertionError" message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.validUsernameInvalidPassword(LoginPageWhenLoggedOutTest.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- validUsernameInvalidPassword -->
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="1.284"/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="1.205"/>
</testsuite> <!-- Chrome test -->
