<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-60T9RMS" failures="8" tests="25" name="tests.login_page.LoginPageWhenLoggedOutTest" time="75.236" errors="0" timestamp="2023-02-06T21:07:49 CET" skipped="0">
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="noPassword" time="3.482"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="1.979"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="6.578">
    <failure message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.invalidUsernameValidPassword(LoginPageWhenLoggedOutTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- invalidUsernameValidPassword -->
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="3.170">
    <failure message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.validUsernameInvalidPassword(LoginPageWhenLoggedOutTest.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- validUsernameInvalidPassword -->
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="2.330"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="profileButtonNotDisplayed" time="0.777"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="3.804"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="3.085"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="1.817"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="1.810"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="3.838">
    <failure message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.invalidUsernameValidPassword(LoginPageWhenLoggedOutTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- invalidUsernameValidPassword -->
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="5.290">
    <failure message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.invalidUsernameValidPassword(LoginPageWhenLoggedOutTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- invalidUsernameValidPassword -->
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="noUsernameNoPassword" time="1.182"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="4.526">
    <failure message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.invalidUsernameValidPassword(LoginPageWhenLoggedOutTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- invalidUsernameValidPassword -->
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="logoutButtonNotDisplayed" time="0.824"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="1.915"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="1.927"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="4.971">
    <failure message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.validUsernameInvalidPassword(LoginPageWhenLoggedOutTest.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- validUsernameInvalidPassword -->
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="1.874"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="3.261">
    <failure message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.validUsernameInvalidPassword(LoginPageWhenLoggedOutTest.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- validUsernameInvalidPassword -->
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="invalidUsernameValidPassword" time="2.203"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="loggedInUserNameNotShown" time="0.903"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="existingUserCanLogIn" time="6.879"/>
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="validUsernameInvalidPassword" time="3.397">
    <failure message="Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message not as expected expected [Invalid username or password!] but found [Failed waiting for error msg.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at tests.login_page.LoginPageWhenLoggedOutTest.validUsernameInvalidPassword(LoginPageWhenLoggedOutTest.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- validUsernameInvalidPassword -->
  <system-out/>
  <testcase classname="tests.login_page.LoginPageWhenLoggedOutTest" name="noUsername" time="3.414"/>
  <system-out/>
</testsuite> <!-- tests.login_page.LoginPageWhenLoggedOutTest -->
